In [1]:
import re
import colorsys

def detect_color_type(color):
    """Detect the color format based on the input."""
    if isinstance(color, str):
        if color.startswith('#'):
            return 'hex'
        elif 'hsl' in color:
            return 'hsl'
    elif isinstance(color, (list, tuple)):
        if len(color) == 3:
            return 'rgb'
        elif len(color) == 4:
            return 'rgba'
    return None

def hex_to_rgb(hex_color):
    """Convert HEX to RGB."""
    hex_color = hex_color.lstrip('#')
    lv = len(hex_color)
    return tuple(int(hex_color[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

def rgb_to_hex(rgb_color):
    """Convert RGB to HEX."""
    return '#{:02x}{:02x}{:02x}'.format(*rgb_color)

def rgba_to_hex(rgba_color):
    """Convert RGBA to HEX (ignoring alpha)."""
    return rgb_to_hex(rgba_color[:3])

def hex_to_rgba(hex_color, alpha=1):
    """Convert HEX to RGBA."""
    return hex_to_rgb(hex_color) + (alpha,)

def rgb_to_hsl(rgb_color):
    """Convert RGB to HSL."""
    r, g, b = [x / 255.0 for x in rgb_color]
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return int(h * 360), int(s * 100), int(l * 100)

def hsl_to_rgb(hsl_color):
    """Convert HSL to RGB."""
    h, s, l = hsl_color
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return int(r * 255), int(g * 255), int(b * 255)

def convert_color(color, to_format, alpha=1):
    """Convert the color to the desired format."""
    from_format = detect_color_type(color)
    
    if not from_format:
        raise ValueError("Unsupported color format.")
    
    if from_format == 'hex':
        rgb_color = hex_to_rgb(color)
    elif from_format == 'rgb':
        rgb_color = color
    elif from_format == 'rgba':
        rgb_color = color[:3]
    elif from_format == 'hsl':
        rgb_color = hsl_to_rgb(color)
    
    if to_format == 'hex':
        return rgb_to_hex(rgb_color)
    elif to_format == 'rgba':
        return rgb_color + (alpha,)
    elif to_format == 'rgb':
        return rgb_color
    elif to_format == 'hsl':
        return rgb_to_hsl(rgb_color)
    
    raise ValueError(f"Unsupported target format: {to_format}")

# Example usage:
print(convert_color("#34a1eb", "rgba", alpha=0.8))  # HEX to RGBA
print(convert_color((52, 161, 235), "hex"))         # RGB to HEX
print(convert_color((52, 161, 235), "hsl"))         # RGB to HSL
print(convert_color("hsl(206, 77%, 56%)", "rgb"))   # HSL to RGB


(52, 161, 235, 0.8)
#34a1eb
(204, 82, 56)


ValueError: too many values to unpack (expected 3)

In [5]:
import re
import colorsys

def detect_color_type(color):
    """Detect the color format based on the input."""
    if isinstance(color, str):
        if color.startswith('#'):
            return 'hex'
        elif 'hsl' in color:
            return 'hsl'
    elif isinstance(color, (list, tuple)):
        if len(color) == 3:
            return 'rgb'
        elif len(color) == 4:
            return 'rgba'
    return None

def parse_hsl_string(hsl_string):
    """Parse HSL string into a tuple of (h, s, l)."""
    hsl_values = re.findall(r'\d+', hsl_string)
    return int(hsl_values[0]), int(hsl_values[1]), int(hsl_values[2])

def hex_to_rgb(hex_color):
    """Convert HEX to RGB."""
    hex_color = hex_color.lstrip('#')
    lv = len(hex_color)
    return tuple(int(hex_color[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

def rgb_to_hex(rgb_color):
    """Convert RGB to HEX."""
    return '#{:02x}{:02x}{:02x}'.format(*rgb_color)

def rgba_to_hex(rgba_color):
    """Convert RGBA to HEX (ignoring alpha)."""
    return rgb_to_hex(rgba_color[:3])

def hex_to_rgba(hex_color, alpha=1):
    """Convert HEX to RGBA."""
    return hex_to_rgb(hex_color) + (alpha,)

def rgb_to_hsl(rgb_color):
    """Convert RGB to HSL."""
    r, g, b = [x / 255.0 for x in rgb_color]
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return int(h * 360), int(s * 100), int(l * 100)

def hsl_to_rgb(hsl_color):
    """Convert HSL to RGB."""
    h, s, l = hsl_color
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return int(r * 255), int(g * 255), int(b * 255)

def convert_color(color, to_format, alpha=1):
    """Convert the color to the desired format."""
    from_format = detect_color_type(color)
    
    if not from_format:
        raise ValueError("Unsupported color format.")
    
    if from_format == 'hex':
        rgb_color = hex_to_rgb(color)
    elif from_format == 'rgb':
        rgb_color = color
    elif from_format == 'rgba':
        rgb_color = color[:3]
    elif from_format == 'hsl':
        hsl_color = parse_hsl_string(color)
        rgb_color = hsl_to_rgb(hsl_color)
    
    if to_format == 'hex':
        return rgb_to_hex(rgb_color)
    elif to_format == 'rgba':
        return rgb_color + (alpha,)
    elif to_format == 'rgb':
        return rgb_color
    elif to_format == 'hsl':
        return rgb_to_hsl(rgb_color)
    
    raise ValueError(f"Unsupported target format: {to_format}")

# Example usage:
print(convert_color("#34a1eb", "rgba", alpha=0.8))  # HEX to RGBA
print(convert_color((52, 161, 235), "hex"))         # RGB to HEX
print(convert_color((52, 161, 235), "hsl"))         # RGB to HSL
print(convert_color("hsl(206, 77%, 56%)", "rgb"))   # HSL to RGB
print(convert_color("#34a1eb1b", "rgba"))  # HEX to RGBA
print(convert_color((52, 161, 235,100), "hex"))     # RGBA to HEX


(52, 161, 235, 0.8)
#34a1eb
(204, 82, 56)
(56, 154, 229)
(52, 161, 235, 27, 1)
#34a1eb


In [11]:
import re
import colorsys

def detect_color_type(color):
    """Detect the color format based on the input."""
    if isinstance(color, str):
        if color.startswith('#'):
            return 'hex'
        elif 'hsl' in color:
            return 'hsl'
    elif isinstance(color, (list, tuple)):
        if len(color) == 3:
            return 'rgb'
        elif len(color) == 4:
            return 'rgba'
    return None

def parse_hsl_string(hsl_string):
    """Parse HSL string into a tuple of (h, s, l)."""
    hsl_values = re.findall(r'\d+', hsl_string)
    return int(hsl_values[0]), int(hsl_values[1]), int(hsl_values[2])

def hex_to_rgb(hex_color):
    """Convert HEX to RGB."""
    hex_color = hex_color.lstrip('#')
    lv = len(hex_color)
    return tuple(int(hex_color[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

def rgb_to_hex(rgb_color):
    """Convert RGB to HEX."""
    return '#{:02x}{:02x}{:02x}'.format(*rgb_color)

def rgba_to_hex(rgba_color):
    """Convert RGBA to HEX (including alpha)."""
    return '#{:02x}{:02x}{:02x}{:02x}'.format(rgba_color[0], rgba_color[1], rgba_color[2], int(rgba_color[3] * 255))

def hex_to_rgba(hex_color, alpha=1):
    """Convert HEX to RGBA. If HEX has an alpha value, use it; otherwise, use the default."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 8:
        r, g, b, a = tuple(int(hex_color[i:i+2], 16) for i in range(0, 8, 2))
        return r, g, b, a
    else:
        r, g, b = hex_to_rgb(hex_color)
        return r, g, b, alpha

def rgb_to_hsl(rgb_color):
    """Convert RGB to HSL."""
    r, g, b = [x / 255.0 for x in rgb_color]
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return int(h * 360), int(s * 100), int(l * 100)

def hsl_to_rgb(hsl_color):
    """Convert HSL to RGB."""
    h, s, l = hsl_color
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return int(r * 255), int(g * 255), int(b * 255)

def convert_color(color, to_format, alpha=1):
    """Convert the color to the desired format."""
    from_format = detect_color_type(color)
    
    if not from_format:
        raise ValueError("Unsupported color format.")
    
    if from_format == 'hex':
        rgba_color = hex_to_rgba(color, alpha)
        rgb_color = rgba_color[:3]
    elif from_format == 'rgb':
        rgb_color = color
        rgba_color = rgb_color + (alpha,)
    elif from_format == 'rgba':
        rgb_color = color[:3]
        rgba_color = color
    elif from_format == 'hsl':
        hsl_color = parse_hsl_string(color)
        rgb_color = hsl_to_rgb(hsl_color)
        rgba_color = rgb_color + (alpha,)
    
    if to_format == 'hex':
        return rgb_to_hex(rgb_color)
    elif to_format == 'rgba':
        return rgba_color
    elif to_format == 'rgb':
        return rgb_color
    elif to_format == 'hsl':
        return rgb_to_hsl(rgb_color)
    
    raise ValueError(f"Unsupported target format: {to_format}")

# Example usage:
print(convert_color("#1a3d4d64", "rgba"))  # HEX to RGBA


(26, 61, 77, 100)


In [12]:
import re
import colorsys
import numpy as np

def detect_color_type(color):
    """Detect the color format based on the input."""
    if isinstance(color, str):
        if color.startswith('#'):
            return 'hex'
        elif 'hsl' in color:
            return 'hsl'
    elif isinstance(color, (list, tuple)):
        if len(color) == 3:
            return 'rgb'
        elif len(color) == 4:
            return 'rgba'
    return None

def parse_hsl_string(hsl_string):
    """Parse HSL string into a tuple of (h, s, l)."""
    hsl_values = re.findall(r'\d+', hsl_string)
    return int(hsl_values[0]), int(hsl_values[1]), int(hsl_values[2])

def hex_to_rgb(hex_color):
    """Convert HEX to RGB."""
    hex_color = hex_color.lstrip('#')
    lv = len(hex_color)
    return tuple(int(hex_color[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

def rgb_to_hex(rgb_color):
    """Convert RGB to HEX."""
    return '#{:02x}{:02x}{:02x}'.format(*rgb_color)

def rgba_to_hex(rgba_color):
    """Convert RGBA to HEX (including alpha)."""
    return '#{:02x}{:02x}{:02x}{:02x}'.format(rgba_color[0], rgba_color[1], rgba_color[2], int(rgba_color[3] * 255))

def hex_to_rgba(hex_color, alpha=1):
    """Convert HEX to RGBA. If HEX has an alpha value, use it; otherwise, use the default."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 8:
        r, g, b, a = tuple(int(hex_color[i:i+2], 16) for i in range(0, 8, 2))
        return r, g, b, a
    else:
        r, g, b = hex_to_rgb(hex_color)
        return r, g, b, alpha

def rgb_to_hsl(rgb_color):
    """Convert RGB to HSL."""
    r, g, b = [x / 255.0 for x in rgb_color]
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return int(h * 360), int(s * 100), int(l * 100)

def hsl_to_rgb(hsl_color):
    """Convert HSL to RGB."""
    h, s, l = hsl_color
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return int(r * 255), int(g * 255), int(b * 255)

def convert_color(color, to_format, alpha=1):
    """Convert the color to the desired format."""
    from_format = detect_color_type(color)
    
    if not from_format:
        raise ValueError("Unsupported color format.")
    
    has_alpha = False
    
    if from_format == 'hex':
        rgba_color = hex_to_rgba(color, alpha)
        rgb_color = rgba_color[:3]
        has_alpha = len(color) == 9  # HEX with alpha has 9 characters (including #)
    elif from_format == 'rgb':
        rgb_color = color
        rgba_color = rgb_color + (alpha,)
    elif from_format == 'rgba':
        rgb_color = color[:3]
        rgba_color = color
        has_alpha = True
    elif from_format == 'hsl':
        hsl_color = parse_hsl_string(color)
        rgb_color = hsl_to_rgb(hsl_color)
        rgba_color = rgb_color + (alpha,)
    
    if has_alpha:
        alpha = rgba_color[3]  # Use the alpha from the input color
    
    if to_format == 'hex':
        return np.array(rgb_to_hex(rgb_color))
    elif to_format == 'rgba':
        return np.array(rgba_color[:3] + (alpha,))
    elif to_format == 'rgb':
        return np.array(rgb_color)
    elif to_format == 'hsl':
        return np.array(rgb_to_hsl(rgb_color))
    
    raise ValueError(f"Unsupported target format: {to_format}")

# Example usage:
print(convert_color("#34a1eb1b", "rgba"))  # HEX with alpha to RGBA (as a NumPy array)
print(convert_color((52, 161, 235, 0.5), "rgba", alpha=0.8))  # RGBA input, ignore default alpha (as a NumPy array)


[ 52 161 235  27]
[ 52.  161.  235.    0.5]


In [ ]:
import colorsys




In [14]:
# from convert_color 
import convert_color 
grid_color          = "#252525ff"
grid_color          = (30, 30, 30, 255)
line_color          = (196, 21, 30, 255)
background_color    = (0, 0, 0, 255)
table_color         = (30, 30, 30, 255)
grid_color          = convert_color.convert_color(grid_color, "rgba") / 255
line_color          = convert_color.convert_color(line_color, "rgba")/ 255
background_color    = convert_color.convert_color(background_color, "rgba")/ 255
table_color         = convert_color.convert_color(table_color, "rgba")/ 255
print(grid_color)

[0.11764706 0.11764706 0.11764706 1.        ]


In [15]:
from reportlab.lib import colors
import re
import numpy as np

def hex_to_rgba(hex_color, alpha=1.0):
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 8:  # HEX with alpha (e.g., #RRGGBBAA)
        r, g, b, a = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4, 6))
        return np.array([r, g, b, a / 255.0])
    elif len(hex_color) == 6:  # HEX without alpha (e.g., #RRGGBB)
        r, g, b = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
        return np.array([r, g, b, alpha])
    elif len(hex_color) == 4:  # Short HEX with alpha (e.g., #RGBA)
        r, g, b, a = tuple(int(hex_color[i:i+1] * 2, 16) for i in (0, 1, 2, 3))
        return np.array([r, g, b, a / 255.0])
    elif len(hex_color) == 3:  # Short HEX without alpha (e.g., #RGB)
        r, g, b = tuple(int(hex_color[i:i+1] * 2, 16) for i in (0, 1, 2))
        return np.array([r, g, b, alpha])
    else:
        raise ValueError("Invalid HEX color format.")

def convert_to_rgba(color, default_alpha=1.0):
    if isinstance(color, (list, tuple)) and len(color) == 3:  # RGB
        r, g, b = color
        return np.array([r, g, b, default_alpha])
    elif isinstance(color, (list, tuple)) and len(color) == 4:  # RGBA
        return np.array(color)
    elif isinstance(color, str) and re.match(r'^#(?:[0-9a-fA-F]{3,8})$', color):  # HEX
        return hex_to_rgba(color, alpha=default_alpha)
    else:
        raise ValueError("Unsupported color format.")

# Example usage
rgba_color = convert_to_rgba([52, 161, 235])  # RGB to RGBA
print(rgba_color)  # Output: [ 52 161 235   1]

rgba_color = convert_to_rgba('#34A1EB')  # HEX to RGBA
print(rgba_color)  # Output: [ 52 161 235   1]


[ 52. 161. 235.   1.]
[ 52. 161. 235.   1.]


In [16]:
from reportlab.lib.colors import hex2rgb, rgb2rgb
import numpy as np

def color_to_rgba(color, opacity=1.0):
    """
    Converts a color from HEX, RGB, or RGBA to RGBA format.

    Args:
        color (str or tuple): The color in HEX, RGB, or RGBA format.
        opacity (float): The opacity value to use if the input color is not in RGBA format.

    Returns:
        np.ndarray: The color in RGBA format as a NumPy array.
    """
    if isinstance(color, str):
        if color.startswith('#'):
            # HEX color format (e.g., "#RRGGBB" or "#RRGGBBAA")
            hex_color = color.lstrip('#')
            if len(hex_color) == 8:
                # HEX with alpha
                r, g, b, a = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16), int(hex_color[6:8], 16)
            elif len(hex_color) == 6:
                # HEX without alpha
                r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
                a = int(opacity * 255)  # Convert opacity to alpha value
            else:
                raise ValueError("Invalid HEX color format")
            return np.array([r, g, b, a], dtype=np.uint8)
        
        elif color.startswith('rgb'):
            # RGB color format (e.g., "rgb(r, g, b)")
            rgb_color = color[color.index('(')+1:color.index(')')].split(',')
            r, g, b = int(rgb_color[0].strip()), int(rgb_color[1].strip()), int(rgb_color[2].strip())
            return np.array([r, g, b, int(opacity * 255)], dtype=np.uint8)
        
        elif color.startswith('rgba'):
            # RGBA color format (e.g., "rgba(r, g, b, a)")
            rgba_color = color[color.index('(')+1:color.index(')')].split(',')
            r, g, b, a = int(rgba_color[0].strip()), int(rgba_color[1].strip()), int(rgba_color[2].strip()), int(float(rgba_color[3].strip()) * 255)
            return np.array([r, g, b, a], dtype=np.uint8)
        
        else:
            raise ValueError("Unsupported color format")
    
    elif isinstance(color, tuple) and len(color) == 4:
        # Assuming color is in RGBA format (tuple)
        return np.array(color, dtype=np.uint8)
    
    elif isinstance(color, tuple) and len(color) == 3:
        # RGB format (tuple)
        return np.array([*color, int(opacity * 255)], dtype=np.uint8)
    
    else:
        raise ValueError("Unsupported color format")

# Example usage
hex_color = "#3498db"  # HEX color without alpha
rgb_color = "rgb(52, 161, 235)"  # RGB color
rgba_color = "rgba(52, 161, 235, 0.8)"  # RGBA color
opacity = 0.5

print(color_to_rgba(hex_color, opacity))
print(color_to_rgba(rgb_color, opacity))
print(color_to_rgba(rgba_color))


ImportError: cannot import name 'hex2rgb' from 'reportlab.lib.colors' (/home/shubham/data1/Workspace/Python/Patterned-PDF-Generator/.venv/lib/python3.12/site-packages/reportlab/lib/colors.py)